from __future__ import annotations

from app.models import (
    AuthorizedDealer,
    DealerProfile,
    Membership,
    MonitoringMode,
    NotificationChannel,
    NotificationDestination,
    ObservedAsset,
    ObservedPlace,
    Organization,
    OrganizationType,
    SourceType,
    User,
    UserRole,
)


def demo_organizations() -> list[Organization]:
    return [
        Organization(id="org-platform", name="Vigilante Platform", organization_type=OrganizationType.PLATFORM),
        Organization(id="org-yamaha-network", name="Yamaha Red Oficial", organization_type=OrganizationType.NETWORK),
        Organization(id="org-dealer-bello", name="Motoblu Bello", organization_type=OrganizationType.DEALER),
        Organization(id="org-dealer-itagui", name="Motoblu Itagui", organization_type=OrganizationType.DEALER),
        Organization(id="org-dealer-guayabal", name="Mundo Yamaha Guayabal", organization_type=OrganizationType.DEALER),
    ]


def demo_users(password_hasher) -> list[User]:
    return [
        User(
            id="user-super-admin",
            email="operator@vigilante.local",
            full_name="Super Admin Vigilante",
            password_hash=password_hasher("change-me"),
        ),
        User(
            id="user-yamaha-admin",
            email="yamaha@vigilante.local",
            full_name="Admin Yamaha",
            password_hash=password_hasher("yamaha-demo"),
        ),
        User(
            id="user-dealer-bello-admin",
            email="bello@motoblu.local",
            full_name="Admin Motoblu Bello",
            password_hash=password_hasher("dealer-demo"),
        ),
        User(
            id="user-dealer-bello-member",
            email="asesor.bello@motoblu.local",
            full_name="Asesor Motoblu Bello",
            password_hash=password_hasher("dealer-demo"),
        ),
    ]


def demo_memberships() -> list[Membership]:
    return [
        Membership(
            id="membership-super-admin",
            user_id="user-super-admin",
            organization_id="org-platform",
            role=UserRole.SUPER_ADMIN,
        ),
        Membership(
            id="membership-yamaha-admin",
            user_id="user-yamaha-admin",
            organization_id="org-yamaha-network",
            role=UserRole.YAMAHA_ADMIN,
        ),
        Membership(
            id="membership-bello-admin",
            user_id="user-dealer-bello-admin",
            organization_id="org-dealer-bello",
            role=UserRole.DEALER_ADMIN,
        ),
        Membership(
            id="membership-bello-member",
            user_id="user-dealer-bello-member",
            organization_id="org-dealer-bello",
            role=UserRole.DEALER_MEMBER,
        ),
    ]


def demo_notification_destinations() -> list[NotificationDestination]:
    events = ["new_alert", "case_confirmed", "case_ready_for_google", "status_changed"]
    return [
        NotificationDestination(
            id="notification-yamaha-email",
            organization_id="org-yamaha-network",
            channel=NotificationChannel.EMAIL,
            target="yamaha-alertas@example.com",
            subscribed_events=events,
        ),
        NotificationDestination(
            id="notification-bello-email",
            organization_id="org-dealer-bello",
            channel=NotificationChannel.EMAIL,
            target="bello-alertas@example.com",
            subscribed_events=events,
        ),
    ]


def demo_dealers() -> list[AuthorizedDealer]:
    return [
        AuthorizedDealer(
            id="dealer-bello",
            organization_id="org-dealer-bello",
            name="Motoblu Bello",
            city="Bello",
            address="Autopista Norte 45, Bello",
            phone_numbers=["6044440101", "573014440101"],
            latitude=6.3364,
            longitude=-75.5552,
        ),
        AuthorizedDealer(
            id="dealer-itagui",
            organization_id="org-dealer-itagui",
            name="Motoblu Itagui",
            city="Itagui",
            address="Carrera 52 76-20, Itagui",
            phone_numbers=["6044440202", "573014440202"],
            latitude=6.1719,
            longitude=-75.6114,
        ),
        AuthorizedDealer(
            id="dealer-guayabal",
            organization_id="org-dealer-guayabal",
            name="Mundo Yamaha Guayabal",
            city="Medellin",
            address="Calle 10 55-87, Medellin",
            phone_numbers=["6044440303", "573014440303"],
            latitude=6.2157,
            longitude=-75.5918,
        ),
    ] + official_bogota_dealers()


def demo_profiles() -> list[DealerProfile]:
    return [
        DealerProfile(
            id="profile-bello",
            dealer_id="dealer-bello",
            organization_id="org-dealer-bello",
            name="Motoblu Bello",
            google_place_id="place-official-bello",
            gbp_location_id="locations/1001",
            monitoring_mode=MonitoringMode.GBP_PUSH,
        ),
        DealerProfile(
            id="profile-itagui",
            dealer_id="dealer-itagui",
            organization_id="org-dealer-itagui",
            name="Motoblu Itagui",
            google_place_id="place-official-itagui",
            gbp_location_id="locations/1002",
            monitoring_mode=MonitoringMode.GBP_PUSH,
        ),
        DealerProfile(
            id="profile-guayabal",
            dealer_id="dealer-guayabal",
            organization_id="org-dealer-guayabal",
            name="Mundo Yamaha Guayabal",
            google_place_id="place-official-guayabal",
            monitoring_mode=MonitoringMode.PUBLIC_SCAN,
        ),
    ] + official_bogota_profiles()


def official_bogota_dealers() -> list[AuthorizedDealer]:
    source_label = "Fuente oficial Incolmotos Yamaha"
    return [
        AuthorizedDealer(
            id="dealer-official-yamaha-3182",
            organization_id="org-yamaha-network",
            name="Motorsportbikes sas",
            city="Bogotá D.C.",
            address="Calle 23 # 32-55 puente aranda",
            phone_numbers=["3234661501"],
            latitude=4.624511216227102,
            longitude=-74.0863544667085,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2521",
            organization_id="org-yamaha-network",
            name="ACEITAR CHAPINERO 67",
            city="Bogotá D.C.",
            address="CALLE 67 # 8 -47",
            phone_numbers=["6012119418", "3208764116"],
            latitude=4.651488,
            longitude=-74.059667,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3202",
            organization_id="org-yamaha-network",
            name="Aceitar S.A.S",
            city="Bogotá D.C.",
            address="Avenida 19 # 134ª - 23",
            phone_numbers=["3202713639"],
            latitude=4.719565,
            longitude=-74.046744,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2519",
            organization_id="org-yamaha-network",
            name="ACEITAR SUBA 116",
            city="Bogotá D.C.",
            address="CALLE 116 # 60-13",
            phone_numbers=["6012533795", "3107996608"],
            latitude=4.69983,
            longitude=-74.070412,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2667",
            organization_id="org-yamaha-network",
            name="INCOLMOTOS YAMAHA",
            city="Bogotá D.C.",
            address="CL 71 C 29B-36",
            phone_numbers=["6017420441", "3148242099"],
            latitude=4.666766951694592,
            longitude=-74.07312029998977,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-188",
            organization_id="org-yamaha-network",
            name="INCOLMOTOS YAMAHA",
            city="Bogotá D.C.",
            address="Av 30 #63-10",
            phone_numbers=["6017448591", "3104424206"],
            latitude=4.652721686938349,
            longitude=-74.07809346923813,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3169",
            organization_id="org-yamaha-network",
            name="Moto Nipon Cl 80",
            city="Bogotá D.C.",
            address="Transversal 89 #80-15",
            phone_numbers=["3103382876"],
            latitude=4.70382378294734,
            longitude=-74.10208803002318,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3115",
            organization_id="org-yamaha-network",
            name="MOTO NOVA",
            city="Bogotá D.C.",
            address="CL 73 67 73",
            phone_numbers=["3156958119"],
            latitude=4.67799,
            longitude=-74.08495,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3093",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S",
            city="Bogotá D.C.",
            address="AUT NORTE 127 A 09",
            phone_numbers=["6013904947", "3183999475"],
            latitude=4.709237128962763,
            longitude=-74.05418157694143,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2671",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S 7 DE AGOSTO",
            city="Bogotá D.C.",
            address="CR 24 No. 68-35",
            phone_numbers=["6018014702", "3176570502"],
            latitude=4.660006582870857,
            longitude=-74.06950235404386,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2578",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S ALQUERIA",
            city="Bogotá D.C.",
            address="AV CL 45 A SUR 52 A 09",
            phone_numbers=["6014911582", "6012730314", "3183999475"],
            latitude=4.594413077706614,
            longitude=-74.13551688268149,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2576",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S BOSA",
            city="Bogotá D.C.",
            address="CR 80 A 63 09 SUR BOSA",
            phone_numbers=["6014929079", "3183999475"],
            latitude=4.6079561,
            longitude=-74.1855685,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2577",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S FONTIBON",
            city="Bogotá D.C.",
            address="CL 17 No. 103B-83",
            phone_numbers=["6013003488", "3183594957"],
            latitude=4.67624695088965,
            longitude=-74.14808839644489,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2573",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S KENNEDY",
            city="Bogotá D.C.",
            address="TV 73 C BIS A 38 34 SUR KENNEDY",
            phone_numbers=["6012730314", "6012735774", "3183999475"],
            latitude=4.61802478884414,
            longitude=-74.14853332157095,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2579",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S PALOQUEMAO",
            city="Bogotá D.C.",
            address="AV CRA 30 17 36 PALOQUEMAO",
            phone_numbers=["6017036714", "3183352952"],
            latitude=4.6168970519504935,
            longitude=-74.08995281717674,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2575",
            organization_id="org-yamaha-network",
            name="MOTOAUTO STORE S.A.S VENECIA",
            city="Bogotá D.C.",
            address="AUT SUR AV CL 45 A SUR 51 45 BRR VENECIA",
            phone_numbers=["3183352782", "3183999475"],
            latitude=4.594819,
            longitude=-74.138454,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3163",
            organization_id="org-yamaha-network",
            name="Motoauto Store Suba",
            city="Bogotá D.C.",
            address="CL 145 # 94 A24",
            phone_numbers=["3242387616"],
            latitude=4.739257,
            longitude=-74.087155,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3180",
            organization_id="org-yamaha-network",
            name="Motoauto Yamaha Plaza de las Americas",
            city="Bogotá D.C.",
            address="Dirección Av. 1 de Mayo #70b-24",
            phone_numbers=["3045396943"],
            latitude=4.616001,
            longitude=-74.136744,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3130",
            organization_id="org-yamaha-network",
            name="Motonipón",
            city="Bogotá D.C.",
            address="AV BOYACÁ NÚMERO 8 B 05*",
            phone_numbers=["3105309933"],
            latitude=4.638878595469384,
            longitude=-74.13641267116434,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3082",
            organization_id="org-yamaha-network",
            name="MOTONIPON SAS",
            city="Bogotá D.C.",
            address="AV CARACAS 13 A 38 SUR",
            phone_numbers=["3174231251"],
            latitude=4.58518765422297,
            longitude=-74.09654784090108,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3131",
            organization_id="org-yamaha-network",
            name="Motonipon SAS",
            city="Bogotá D.C.",
            address="AV BOYACÁ NÚMERO 8 B 05",
            phone_numbers=["3105309933"],
            latitude=4.640963624554959,
            longitude=-74.13683885805928,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2691",
            organization_id="org-yamaha-network",
            name="MOTONIPON SAS",
            city="Bogotá D.C.",
            address="CENTRO CIAL PASEO VILLA DEL RIO YAMAHA",
            phone_numbers=["3174231251"],
            latitude=4.598832,
            longitude=-74.153458,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2478",
            organization_id="org-yamaha-network",
            name="MOTOR UNO",
            city="Bogotá D.C.",
            address="AV BOYACA 69 A 06",
            phone_numbers=["6012510122", "3142957828"],
            latitude=4.683844,
            longitude=-74.097115,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3053",
            organization_id="org-yamaha-network",
            name="MOTOR UNO",
            city="Bogotá D.C.",
            address="CRA 80 42A 55 SUR",
            phone_numbers=["6017465390", "6017465391"],
            latitude=4.6226381,
            longitude=-74.1668833,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2483",
            organization_id="org-yamaha-network",
            name="MOTOR UNO AURES",
            city="Bogotá D.C.",
            address="CL 129 D 104 B 04 AURES",
            phone_numbers=["6018027109", "6012881998", "3185172216"],
            latitude=4.730349,
            longitude=-74.1015766,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2465",
            organization_id="org-yamaha-network",
            name="MOTOS EL CONDOR",
            city="Bogotá D.C.",
            address="AV CARACAS 15 80",
            phone_numbers=["3208631053"],
            latitude=4.605754,
            longitude=-74.0782586,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2466",
            organization_id="org-yamaha-network",
            name="MOTOS EL CONDOR",
            city="Bogotá D.C.",
            address="AV CL 80 64 19",
            phone_numbers=["6014873700"],
            latitude=4.681807,
            longitude=-74.077748,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-2420",
            organization_id="org-yamaha-network",
            name="YAMAHA MOTOS",
            city="Bogotá D.C.",
            address="AV 1 DE MAYO 28 31",
            phone_numbers=["6018770020", "3134996586"],
            latitude=4.590231,
            longitude=-74.109901,
            influence_label=source_label,
        ),
        AuthorizedDealer(
            id="dealer-official-yamaha-3085",
            organization_id="org-yamaha-network",
            name="YAMAHA MOTOS BOGOTA NORTE",
            city="Bogotá D.C.",
            address="Carrera 45 # 168- 43",
            phone_numbers=["3232235767"],
            latitude=4.7499211,
            longitude=-74.0473469,
            influence_label=source_label,
        ),
    ]


def official_bogota_profiles() -> list[DealerProfile]:
    return [
        DealerProfile(
            id=f"profile-{dealer.id.removeprefix('dealer-')}",
            dealer_id=dealer.id,
            organization_id=dealer.organization_id,
            name=dealer.name,
            monitoring_mode=MonitoringMode.PUBLIC_SCAN,
        )
        for dealer in official_bogota_dealers()
    ]


def suspicious_places() -> list[ObservedPlace]:
    return [
        ObservedPlace(
            id="obs-place-1",
            place_id="clone-bello-1",
            name="Yamaha Bello Principal",
            address="Diagonal 50 45-12, Bello",
            phone_number="3019998888",
            category="motorcycle_dealer",
            latitude=6.3371,
            longitude=-75.5549,
            source_query="yamaha bello",
        ),
        ObservedPlace(
            id="obs-place-2",
            place_id="clone-san-juan-1",
            name="Centro de Entregas Yamaha San Juan",
            address="San Juan 43-12, Medellin",
            phone_number="3007771122",
            category="motorcycle_repair_shop",
            latitude=6.2462,
            longitude=-75.5931,
            source_query="yamaha medellin",
        ),
        ObservedPlace(
            id="obs-place-3",
            place_id="official-guayabal",
            name="Mundo Yamaha Guayabal",
            address="Calle 10 55-87, Medellin",
            phone_number="6044440303",
            category="motorcycle_dealer",
            latitude=6.2157,
            longitude=-75.5918,
            source_query="yamaha guayabal",
        ),
    ]


def suspicious_assets() -> list[ObservedAsset]:
    return [
        ObservedAsset(
            id="asset-1",
            profile_id="profile-bello",
            source_type=SourceType.OFFICIAL_PROFILE_UPDATE,
            review_text="Atencion por Whatsapp 301 999 8888, separa la moto hoy.",
            extracted_text="Yamaha Bello 301 999 8888",
            raw_payload={"uploader": "local-guide-91"},
        ),
        ObservedAsset(
            id="asset-2",
            profile_id="profile-itagui",
            source_type=SourceType.REVIEW_PHOTO,
            review_text="Este es el nuevo numero del concesionario",
            extracted_text="6044440202",
            raw_payload={"uploader": "cliente-real"},
        ),
    ]
